spring:
  application:
    name: ocr

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB


video:
  frame-extractor:
    videoFramesPath: E:\TEMP\ocr\outcome
    interval: 5
    threshold: 0.8